import type { Listing, User, RealBrideStory } from '@/types'

export const MOCK_SELLERS: User[] = [
  {
    id: 'u1',
    email: 'priya@example.com',
    full_name: 'Priya Mehta',
    avatar_url: '',
    role: 'seller',
    location: 'Mumbai, Maharashtra',
    bio: 'Married in 2023 | Sharing my wedding trousseau with love',
    rating: 4.9,
    review_count: 12,
    total_sales: 8,
    verified: true,
    created_at: '2024-01-15T00:00:00Z',
  },
  {
    id: 'u2',
    email: 'ananya@example.com',
    full_name: 'Ananya Sharma',
    avatar_url: '',
    role: 'seller',
    location: 'Delhi, NCR',
    bio: 'Fashion lover | Wedding: Nov 2022 | Letting gorgeous pieces find new homes',
    rating: 5.0,
    review_count: 6,
    total_sales: 4,
    verified: true,
    created_at: '2023-11-10T00:00:00Z',
  },
  {
    id: 'u3',
    email: 'kavya@example.com',
    full_name: 'Kavya Reddy',
    avatar_url: '',
    role: 'seller',
    location: 'Hyderabad, Telangana',
    bio: 'Bride of 2024 | Sabyasachi bride sharing her trousseau',
    rating: 4.8,
    review_count: 3,
    total_sales: 2,
    verified: false,
    created_at: '2024-06-01T00:00:00Z',
  },
]

export const MOCK_LISTINGS: Listing[] = [
  {
    id: 'l1',
    slug: 'gulnaar-sabyasachi-crimson-bridal',
    title: 'Gulnaar — Sabyasachi Crimson Bridal Lehenga',
    description: 'A masterpiece in crimson and gold. This Sabyasachi creation was worn at my December 2023 wedding in Udaipur. Every bead, every thread tells a story of artisanal mastery that took over 600 hours to create.',
    asking_price: 285000,
    original_retail_price: 485000,
    designer: 'Sabyasachi',
    fabric: 'Raw Silk',
    work: 'Hand Embroidery, Zardozi',
    colour: 'Crimson & Gold',
    colour_hex: '#8b1a1a',
    occasion: 'bridal',
    condition: 'worn-once',
    alterations_allowed: false,
    images: [],
    wedding_photos: [
      { url: '', caption: 'Walking into my mandap', is_cover: true },
      { url: '', caption: 'With my mother', is_cover: false },
    ],
    seller_story: {
      title: 'The Lehenga That Made Me Feel Like a Queen',
      body: "When I first saw this lehenga at the Sabyasachi flagship in Mumbai, I knew it was the one. The weight of it in my hands, the way the zardozi caught the light — it felt like wearing a piece of history. My wedding day in Udaipur was everything I dreamed of, and this lehenga was the centre of every photograph. Now it sits in its original box, preserved and loved. I want it to walk into another woman's most beautiful chapter.",
      wedding_date: '2023-12-18',
      wedding_venue: 'Taj Lake Palace',
      wedding_location: 'Udaipur, Rajasthan',
    },
    measurements: {
      bust: 36,
      waist: 30,
      hip: 40,
      length: 42,
      blouse_length: 15,
    },
    size_label: 'M',
    seller_id: 'u1',
    seller: MOCK_SELLERS[0],
    status: 'active',
    views: 847,
    saves: 124,
    created_at: '2024-02-10T00:00:00Z',
    updated_at: '2024-02-10T00:00:00Z',
    discount_percent: 41,
    authenticity_verified: true,
  },
  {
    id: 'l2',
    slug: 'rooh-manish-malhotra-ivory-reception',
    title: 'Rooh — Manish Malhotra Ivory Reception Lehenga',
    description: 'Ethereal ivory and silver for the most special night. Worn at my Delhi reception, this Manish Malhotra lehenga is a dream in real life.',
    asking_price: 185000,
    original_retail_price: 320000,
    designer: 'Manish Malhotra',
    fabric: 'Net & Silk',
    work: 'Sequin, Thread Embroidery',
    colour: 'Ivory & Silver',
    colour_hex: '#f5f0e8',
    occasion: 'reception',
    condition: 'worn-once',
    alterations_allowed: true,
    images: [],
    wedding_photos: [],
    seller_story: {
      title: 'Dancing All Night in Manish Malhotra',
      body: "I chose this lehenga for my reception because I wanted to feel like starlight. The way the sequins move when you dance — there's nothing quite like it. My reception was in November 2022 and I still remember every moment in this. It's now ready for its next chapter.",
      wedding_date: '2022-11-12',
      wedding_venue: 'The Leela Palace',
      wedding_location: 'New Delhi',
    },
    measurements: {
      bust: 34,
      waist: 28,
      hip: 38,
      length: 40,
      blouse_length: 14,
    },
    size_label: 'S',
    seller_id: 'u2',
    seller: MOCK_SELLERS[1],
    status: 'active',
    views: 623,
    saves: 89,
    created_at: '2024-03-05T00:00:00Z',
    updated_at: '2024-03-05T00:00:00Z',
    discount_percent: 42,
    authenticity_verified: true,
  },
  {
    id: 'l3',
    slug: 'kaaynaat-tarun-tahiliani-dusty-rose',
    title: 'Kaaynaat — Tarun Tahiliani Dusty Rose Sangeet',
    description: 'Perfect for sangeet or mehendi. This Tarun Tahiliani piece in dusty rose with intricate mirror work is a showstopper.',
    asking_price: 95000,
    original_retail_price: 175000,
    designer: 'Tarun Tahiliani',
    fabric: 'Georgette',
    work: 'Mirror Work, Gota Patti',
    colour: 'Dusty Rose',
    colour_hex: '#c4837a',
    occasion: 'sangeet',
    condition: 'twice-worn',
    alterations_allowed: true,
    images: [],
    wedding_photos: [],
    seller_story: {
      title: 'Two Nights of Dancing in This Dream',
      body: "I wore this for both my sangeet and mehendi — couldn't resist! Tarun Tahiliani's mirror work catches every fairy light and the colour photographs beautifully. I'm a petite bride and had it altered slightly at the waist, which is included in the description.",
      wedding_date: '2024-02-08',
      wedding_venue: 'Falaknuma Palace',
      wedding_location: 'Hyderabad, Telangana',
    },
    measurements: {
      bust: 32,
      waist: 26,
      hip: 36,
      length: 40,
      blouse_length: 13,
    },
    size_label: 'XS',
    seller_id: 'u3',
    seller: MOCK_SELLERS[2],
    status: 'active',
    views: 412,
    saves: 67,
    created_at: '2024-06-15T00:00:00Z',
    updated_at: '2024-06-15T00:00:00Z',
    discount_percent: 46,
    authenticity_verified: false,
  },
  {
    id: 'l4',
    slug: 'roshni-anita-dongre-blush-mehendi',
    title: 'Roshni — Anita Dongre Blush Pink Mehendi',
    description: 'An Anita Dongre classic in blush pink with intricate floral handwork. Perfect for mehendi or haldi.',
    asking_price: 72000,
    original_retail_price: 145000,
    designer: 'Anita Dongre',
    fabric: 'Mul Cotton',
    work: 'Floral Embroidery, Sitara',
    colour: 'Blush Pink',
    colour_hex: '#e8b4b8',
    occasion: 'mehendi',
    condition: 'worn-once',
    alterations_allowed: false,
    images: [],
    wedding_photos: [],
    seller_story: {
      title: 'My Garden Mehendi Lehenga',
      body: "My mehendi was a garden party in Jaipur and this Anita Dongre felt like it was made for that day. The floral embroidery, the breezy mul cotton — it was light enough to dance in for hours. Worn once, stored in a muslin cloth bag. Looking for a new bride to love it.",
      wedding_date: '2024-01-25',
      wedding_location: 'Jaipur, Rajasthan',
    },
    measurements: {
      bust: 35,
      waist: 29,
      hip: 39,
      length: 41,
      blouse_length: 14,
    },
    size_label: 'M',
    seller_id: 'u1',
    seller: MOCK_SELLERS[0],
    status: 'active',
    views: 298,
    saves: 45,
    created_at: '2024-04-20T00:00:00Z',
    updated_at: '2024-04-20T00:00:00Z',
    discount_percent: 50,
    authenticity_verified: true,
  },
  {
    id: 'l5',
    slug: 'nayaab-abu-sandeep-emerald-festive',
    title: 'Nayaab — Abu Jani Sandeep Khosla Emerald Festive',
    description: 'Stunning emerald green with Chikankari embroidery by the legendary Abu Jani Sandeep Khosla. A piece that is truly heirloom quality.',
    asking_price: 225000,
    original_retail_price: 395000,
    designer: 'Abu Jani Sandeep Khosla',
    fabric: 'Chanderi Silk',
    work: 'Chikankari, Mukaish',
    colour: 'Emerald Green',
    colour_hex: '#2d6a4f',
    occasion: 'festive',
    condition: 'like-new',
    alterations_allowed: false,
    images: [],
    wedding_photos: [],
    seller_story: {
      title: 'A Piece I Will Always Cherish',
      body: "This was gifted to me by my mother-in-law for Diwali. The Chikankari work is unparalleled — every flower hand-stitched by artisans in Lucknow. I wore it once at a family function and it was pristine. I'm parting with it because I want it to be worn, admired, celebrated — not sitting in a wardrobe.",
      wedding_date: '2023-11-12',
      wedding_location: 'Mumbai, Maharashtra',
    },
    measurements: {
      bust: 37,
      waist: 31,
      hip: 41,
      length: 43,
      blouse_length: 16,
    },
    size_label: 'L',
    seller_id: 'u2',
    seller: MOCK_SELLERS[1],
    status: 'active',
    views: 534,
    saves: 98,
    created_at: '2024-05-01T00:00:00Z',
    updated_at: '2024-05-01T00:00:00Z',
    discount_percent: 43,
    authenticity_verified: true,
  },
  {
    id: 'l6',
    slug: 'aarohi-ritu-kumar-teal-party',
    title: 'Aarohi — Ritu Kumar Teal Party Lehenga',
    description: 'Perfect for cocktail parties and festive gatherings. This Ritu Kumar in rich teal with geometric embroidery is a head-turner.',
    asking_price: 48000,
    original_retail_price: 95000,
    designer: 'Ritu Kumar',
    fabric: 'Brocade',
    work: 'Geometric Embroidery, Dabka',
    colour: 'Teal & Gold',
    colour_hex: '#0d7377',
    occasion: 'party',
    condition: 'twice-worn',
    alterations_allowed: true,
    images: [],
    wedding_photos: [],
    seller_story: {
      title: 'The Life of Every Party',
      body: "I bought this for my sister's wedding functions and wore it twice — to the cocktail and the reception. Both times I was stopped for compliments all evening. Ritu Kumar's craftsmanship is timeless. Ready for its next hundred compliments.",
      wedding_date: '2023-08-20',
      wedding_location: 'Pune, Maharashtra',
    },
    measurements: {
      bust: 36,
      waist: 30,
      hip: 40,
      length: 41,
      blouse_length: 15,
    },
    size_label: 'M',
    seller_id: 'u3',
    seller: MOCK_SELLERS[2],
    status: 'active',
    views: 187,
    saves: 31,
    created_at: '2024-07-10T00:00:00Z',
    updated_at: '2024-07-10T00:00:00Z',
    discount_percent: 49,
    authenticity_verified: false,
  },
]

export const MOCK_BRIDE_STORIES: RealBrideStory[] = [
  {
    id: 'b1',
    bride_name: 'Meera & Arjun',
    wedding_date: '2024-02-14',
    wedding_location: 'Udaipur, Rajasthan',
    venue_name: 'Taj Lake Palace',
    story: 'A Valentine\'s Day wedding on the lake. Every moment was a painting.',
    cover_image: '',
    gallery: [],
    tags: ['lakeside', 'rajasthan', 'sabyasachi', 'winter-wedding'],
    likes: 347,
    created_at: '2024-02-20T00:00:00Z',
  },
  {
    id: 'b2',
    bride_name: 'Ishaan & Pooja',
    wedding_date: '2023-11-18',
    wedding_location: 'Jaipur, Rajasthan',
    venue_name: 'Jai Mahal Palace',
    story: 'A royal Rajputana wedding with 400 guests and a night sky full of stars.',
    cover_image: '',
    gallery: [],
    tags: ['palace', 'royal', 'winter', 'anita-dongre'],
    likes: 289,
    created_at: '2023-11-25T00:00:00Z',
  },
]

export const DESIGNERS = [
  'Sabyasachi', 'Manish Malhotra', 'Tarun Tahiliani', 'Anita Dongre',
  'Abu Jani Sandeep Khosla', 'Ritu Kumar', 'Vikram Phadnis', 'Falguni Shane Peacock',
  'Rahul Mishra', 'Anamika Khanna', 'Gaurav Gupta', 'Rimzim Dadu',
]

export const FABRICS = [
  'Raw Silk', 'Net & Silk', 'Georgette', 'Mul Cotton', 'Chanderi Silk',
  'Brocade', 'Banarasi Silk', 'Velvet', 'Organza', 'Tissue Silk',
]

export const WORK_TYPES = [
  'Zardozi', 'Gota Patti', 'Mirror Work', 'Chikankari', 'Sequin',
  'Thread Embroidery', 'Dabka', 'Mukaish', 'Kantha', 'Phulkari',
]
